print("╔════════════════════════════╗")
print("║       DÖVİZ ÇEVİRİCİ       ║")
print("╠════════════════════════════╣")
print("║ 1 - USD → TL               ║")
print("║ 2 - EUR → TL               ║")
print("║ 3 - GBP → TL               ║")
print("║ 4 - TL → USD               ║")
print("║ 5 - TL → EUR               ║")
print("║ 6 - TL → GBP               ║")
print("║ 7 - Ana Menüye Dön         ║")
print("╚════════════════════════════╝")
print("Döviz türünüzü seçin...")
input()
