print("╔═══════════════════════════╗")
print("║   SICAKLIK DÖNÜŞTÜRME     ║")
print("╠═══════════════════════════╣")
print("║ 1 - Celsius → Fahrenheit  ║")
print("║ 2 - Fahrenheit → Celsius  ║")
print("║ 3 - Celsius → Kelvin      ║")
print("║ 4 - Kelvin → Celsius      ║")
print("║ 5 - Ana Menüye Dön        ║")
print("╚═══════════════════════════╝")
print("Çeviri türünü seçiniz...")
input()
