print("╔════════════════════════════════╗")
print("║      PYTHON PROJE MENÜSÜ       ║")
print("╠════════════════════════════════╣")
print("║ 1 - HESAP MAKİNESİ             ║")
print("║ 2 - OYUNLAR                    ║")
print("║ 3 - ÇİZİM ARAÇLARI             ║")
print("║ 4 - TAKVİM                     ║")
print("║ 5 - NOT HESAPLAMA              ║")
print("║ 6 - DÖVİZ ÇEVİRİCİ             ║")
print("║ 7 - SICAKLIK DÖNÜŞTÜRME        ║")
print("║ 8 - ÇIKIŞ                      ║")
print("╚════════════════════════════════╝")
print("Lütfen seçiminizi yapınız...")
input()
